### ISSUE TITLE
老哥，你这给了数据库，可是账号和密码是多少啊

### ISSUE THREAD

**Issue by xuyifu** [angilin/RBAC#2]
= =
账号admin，密码呢

**Comment by xuyifu** [comment]
这个加密算法，没看懂。。。。。好歹给个默认的admin admin啊，，，唉

**Comment by angilin** [comment]
不好意思，忘记写了。
用户名admin，密码1。
加密类是PasswordHash.java，可以运行一下。
打印出来的
1000:44814be71a2b4d44e95f9e33f3eb2fdd94097a362b63792b:a29e42e567a38ce3c3507aeab691231eb4f3a76cc9638508
就是迭代次数:盐:密码。

**Comment by xuyifu** [comment]
谢谢了，在代码看到了迭代次数是1000，可是没看懂盐是怎么来的= =
